### ISSUE TITLE
Failed to scrobble:  Missing data on One Piece episode

### ISSUE THREAD

**Issue by matheusfaustino** [sttz/TraktRoller#2]
Hi, I'm already logged into trakt (using the footer btn) but in this episode https://www.crunchyroll.com/one-piece/episode-338-the-joy-of-seeing-people-the-gentleman-skeletons-true-identity-655299 it shows this:

`Failed to scrobble: Missing data`.

Do I need to do something else?

Thanks for your time

**Comment by sttz** [comment]
This is one of the tricky series to match to Trakt and I haven't figured out a good way yet. The issue is that Crunchyroll makes up their own "seasons", which don't match up with the ones on Trakt. On the other hand, Trakt makes it hard to look up episodes by absolute number, insisting on season-based numbering.

The only way I see right now is to load all episodes from all seasons, which is almost 900 episodes split over 19 seasons and would require 19 separate requests to be sent. I feel this would be close to abusing Trakt's API, so I'll hopefully come up with something better.

**Comment by sttz** [comment]
[1.0.3](https://github.com/sttz/TraktRoller/releases/tag/1.0.3) improves absolute episode number lookup by loading all episode data from the current show (only one request via `/shows/{id}/seasons`). This fixes the lookup of the example you provided, One Piece and Naruto should now scrobble properly.

This is not ideal as for e.g. One Piece, it requires loading more than 700 KB of data.  I've opened an issue with the Trakt API (trakt/api-help#15) to allow looking up episodes by their absolute number to improve this situation.
