### ISSUE TITLE
Incorrect Scrobble with episodes that contain .5 on the number

### ISSUE THREAD

**Issue by justalemon** [sttz/TraktRoller#3]
When you are looking at an episode that contains .5 as part of the episode number, you will get the  normal episode as playing instead of the one that has the .5.

Example: [Sword Art Online II 14.5 (Debriefing)](https://www.crunchyroll.com/sword-art-online/episode-145-debriefing-656653) in Crunchyroll shows [S02E14 (One Little Step)](https://trakt.tv/shows/sword-art-online/seasons/2/episodes/14) instead of [SAO S00E12 (Debriefing)](https://trakt.tv/shows/sword-art-online/seasons/0/episodes/12).

![Screenshot (69)](https://user-images.githubusercontent.com/11861253/56823606-596cf380-6822-11e9-9d91-ffe509ce81ed.png)

**Comment by sttz** [comment]
Thanks for pointing this out! This should now be fixed with version `1.0.5`.

The fractional part got stripped when the episode number was parsed. However, Trakt also does not number these episodes like this (in your example it's "Season 0 Episode 12" on Trakt and "14.5" on Crunchyroll) and therefore straightforward matching is not possible.

TraktRoller now falls back to a manual lookup when it sees a fractional episode number. The only strategy to match these episodes is currently to match the episode title. This is more likely to fail, especially with new episode that often don't yet have titles on Trakt.

I do intend to support overriding the lookup by providing a Trakt ID/URL but I haven't gotten around to the required structural changes and UI work.
